version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  # 追記
  db:
    build: 
      context: ./infra/mysql
      dockerfile: Dockerfile
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 5432:5432 

volumes:
  db-store: